// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqv7Kz5lzcekqYLZXCAYEvgkgzaOwvRpc',
    appId: '1:178835393894:web:e4500a04bb48b92ae0cca7',
    messagingSenderId: '178835393894',
    projectId: 'kbs-motohub',
    authDomain: 'kbs-motohub.firebaseapp.com',
    storageBucket: 'kbs-motohub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9WXHgaYd5htdRP-bYAAf79f0qCYxmi_0',
    appId: '1:178835393894:android:1a0cc14ab4b5cb8ae0cca7',
    messagingSenderId: '178835393894',
    projectId: 'kbs-motohub',
    storageBucket: 'kbs-motohub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0rcbLNmf-MOyWVis_f4H6riBQZNsPf9k',
    appId: '1:178835393894:ios:e14bfd5c613f8932e0cca7',
    messagingSenderId: '178835393894',
    projectId: 'kbs-motohub',
    storageBucket: 'kbs-motohub.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0rcbLNmf-MOyWVis_f4H6riBQZNsPf9k',
    appId: '1:178835393894:ios:e14bfd5c613f8932e0cca7',
    messagingSenderId: '178835393894',
    projectId: 'kbs-motohub',
    storageBucket: 'kbs-motohub.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );
}
